name = "gap"
gleam = ">= 1.0.0"
version = "1.1.3"
description = "A Gleam library for comparing strings/lists and producing a textual (styled) representation of the differences."

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
licences = ["Apache-2.0"]
repository = { type = "github", user = "JohnBjrk", repo = "gap" }
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.34"
gleam_community_ansi = "~> 1.4"

[dev-dependencies]
gleeunit = "~> 1.0"
